export const meta = {
  name: 'multiverse-5d',
  description: 'Research, design (judge panel), implement, verify and polish Quantum 5D Chess with Multiverse Time Travel',
  phases: [
    { title: 'Research', detail: 'three research lenses on 5D chess' },
    { title: 'Design', detail: 'three competing complete designs' },
    { title: 'Judge', detail: 'score the designs and synthesise the final spec' },
    { title: 'Implement', detail: 'rules module and tests' },
    { title: 'UI', detail: 'multiverse view: timelines, present, arrows, submit' },
    { title: 'Verify', detail: 'rules, quantum consistency, performance/AI lenses' },
    { title: 'Fix', detail: 'apply confirmed findings, final re-check' },
  ],
}

const SP = args.handoff
const REPO = '/home/user/Quantum_Chess'
const R = SP + '/research'

const CONTEXT = `Context: "Quantum Chess" is a Nextcloud app (repo ${REPO}). Version 2 adds chess variants, all with the quantum element of the game (read ${REPO}/docs/rules.md for the quantum rules players know). The variants plug into ONE generic quantum layer: read ${SP}/IMPLEMENTING.md (the API as built) and ${SP}/CONTRACT.md, and the code in ${REPO}/src/variants/core/ (quantum.js, world.js, variant.js, orthodox.js, topology.js, ai.js). Key facts: a game state is a list of weighted worlds; each world is an ordinary classical position { sq[], ty[], sd[], board[], x{} }; the variant supplies classical move generation/application and the quantum layer plays each move in all worlds (split, merge, measure, land = roll / pass = link, budget 8, solid roll, game-end roll). The core has a hook solidExtra(world) -> string: structure that must be identical in every world (if a move would make it differ, a roll settles it). nextSide(world, side) decides who moves next (a side may make several moves in one turn). actions(state) -> [{ code, label }] adds buttons such as "Submit turn". layoutOf(state) draws a dynamic layout ({ size, names, cells, layout } with layout.boards, lines, areas, labels, focus: {x, y, zoom}); the board supports zoom and pan. The user asked explicitly (in Dutch) to work out "5D Chess with Multiverse Time Travel and quantum" VERY well: faithful to the real game, fun, clear, and genuinely quantum.`

const RESEARCH = [
  { key: 'rules', prompt: `Research the complete, exact rules of the video game "5D Chess With Multiverse Time Travel" (Thunkspace, 2020): boards and half-turn board states, timelines and their numbering (white-created positive, black-created negative, the 0 line, and the variants with an even number of starting timelines), time coordinates (one step in time = one full turn), which boards are playable, the present and how it moves, active vs inactive timelines (the timeline advantage rule), what a turn is (moving on every playable board in the present that you must move on, optional moves on other playable boards, submitting), when you may submit, travelling to the past (branching a new timeline, where the new board goes), travelling to another timeline's board that is playable (no branch), check, checkmate and softmate, stalemate, draws, and every subtle edge case (moving to a board where it is not your turn is illegal, captures across time, pieces that travel carry nothing else, etc.). Use WebSearch/WebFetch if available (the 5D chess wiki, the game's manual, Reddit rules threads, chess.com articles), else precise knowledge; mark uncertain points.` },
  { key: 'pieces', prompt: `Research how every piece moves in "5D Chess With Multiverse Time Travel": the four axes (file x, rank y, time T, timeline L); rook (one axis), bishop (two axes, equal distance), unicorn (three), dragon (four), queen (any number of axes), king (one step in any combination), knight (2 and 1 on any two axes), pawn and brawn (forward along rank or along timelines, captures, double step, en passant (only on the same board), promotion), princess, royal queen, common king; castling (only on one board); what "one square in time" means (a full turn, i.e. to the board of the same colour to move); which pieces exist in which official variants (Standard, Standard - Turn Zero, Very Small, Small, Simple variants, Tiny, Misc...), their board sizes and setups. Precise tables of movement vectors in (x, y, T, L).` },
  { key: 'engines', prompt: `Research existing open implementations of 5D chess (e.g. "5d-chess-js" by Alexbay218, "5dchess-tools" / "5dchess-engine" in Rust, open-5d-chess, 5D PGN / 5DPGN notation spec) and what they teach: data structures for the multiverse, move generation, how branching and the present are computed, check detection, performance limits, known tricky edge cases, and how the game's UI shows the multiverse (timelines as rows, time as columns, the present line, arrows for time travel, which boards are highlighted, how a player sees where they must still move). Then write concrete recommendations for a compact, fast, browser implementation with bounded size (limits on timelines and history window), and for a clear UI.` },
]

phase('Research')
// Resume support: args.skipResearch = true when handoff/research/multiverse-{rules,pieces,engines}.md exist
const research = args.skipResearch ? ['research present'] : await parallel(RESEARCH.map((r) => () => agent(`${CONTEXT}\n\nYour research lens: ${r.key}.\n${r.prompt}\n\nWrite your findings to ${R}/multiverse-${r.key}.md (complete, precise, with sources and a list of uncertain points). Return a 10-line summary.`, { label: 'research:' + r.key, phase: 'Research' })))

const DESIGNS = [
  { key: 'faithful', angle: 'Maximum fidelity to the real 5D game within the engine: multi-move turns with the present and submit, active timelines, branching, all official piece movements, a standard 8x8 option and a small option, capture-the-king instead of check (Quantum Chess has no check) with a precise argument why that preserves the spirit.' },
  { key: 'playable', angle: 'Clarity and playability for normal players on a laptop and a phone: bounded sizes (timelines, history window), a small default board, very clear UI (what must I still move this turn, where can this piece travel, which timeline is new), speed of move generation and of the computer player, a gentle learning curve, a few clear rules texts.' },
  { key: 'quantum', angle: 'The deepest, most elegant interplay between quantum mechanics and the multiverse: which structure stays classical (timelines, the present) and which can be superposed (pieces on boards), what splitting across time or timelines means, how measurement, rolls and links behave across timelines, why it is fair and understandable, and interesting new tactics that arise.' },
]

phase('Design')
// Resume support: args.skipDesigns lists designs whose file handoff/research/multiverse-design-<key>.md exists
const skipDesigns = new Set(args.skipDesigns ?? [])
const designs = await parallel(DESIGNS.map((d) => () => skipDesigns.has(d.key) ? Promise.resolve('design present: ' + d.key) : agent(`${CONTEXT}\n\nRead the research: ${R}/multiverse-rules.md, ${R}/multiverse-pieces.md, ${R}/multiverse-engines.md, and (if present) ${R}/multiverse.md (an earlier simplified spec).\n\nWrite a COMPLETE design for the variant "multiverse" (Quantum 5D chess) from this angle: ${d.angle}\n\nThe design must be implementable on the existing core without changing it (use the hooks; the only allowed core-side assumptions are those in IMPLEMENTING.md and the hooks named above). It must specify exactly:\n1. Player-facing rules (all of them, including the quantum ones specific to the multiverse), and 5-8 short rules() sentences.\n2. Board size(s) and setup(s) (options), timeline numbering, time, playable boards, present, active timelines, what a turn is, submitting (actions/nextSide), branching, travel, win/draw conditions, limits (max timelines, history window, max ply) and what happens at the limits.\n3. Every piece's movement as vectors in (x, y, T, L) and the pawn rules.\n4. Engine mapping: square encoding (static capacity) and names, the world object (what is in sq/ty/sd/board and in x), how a new board snapshot is created, generate/apply (overrides or descriptors), solidExtra, nextSide, actions, worldResult, evaluate for the computer, performance budget (numbers).\n5. Quantum rules: what can be split/merged/measured, how rolls work across timelines, what stays classical and why.\n6. UI: layoutOf (timelines as rows, time as columns, the present, arrows for travel and branching, labels, focus on the present), what the player sees and clicks.\n7. At least 20 concrete test scenarios with expected results.\nWrite it to ${R}/multiverse-design-${d.key}.md and return a 15-line summary.`, { label: 'design:' + d.key, phase: 'Design' })))

phase('Judge')
const JUDGE_SCHEMA = {
  type: 'object',
  properties: {
    scores: { type: 'array', items: { type: 'object', properties: { design: { type: 'string' }, fidelity: { type: 'number' }, fun: { type: 'number' }, clarity: { type: 'number' }, feasibility: { type: 'number' }, quantum: { type: 'number' }, notes: { type: 'string' } }, required: ['design', 'fidelity', 'fun', 'clarity', 'feasibility', 'quantum', 'notes'] } },
    winner: { type: 'string' },
    graft: { type: 'array', items: { type: 'string' } },
  },
  required: ['scores', 'winner', 'graft'],
}
const judges = await parallel([0, 1].map((i) => () => agent(`${CONTEXT}\n\nYou are judge ${i + 1} of 2. Read the three designs ${R}/multiverse-design-faithful.md, ${R}/multiverse-design-playable.md, ${R}/multiverse-design-quantum.md and the research files ${R}/multiverse-*.md. Score each design 1-10 on fidelity to the real game, fun, clarity for players, feasibility/performance on the existing core (check claims against the code in ${REPO}/src/variants/core), and quantum depth. Be critical: look for rules contradictions, unimplementable parts, performance traps, UI confusion. Name the winner and list the best ideas to graft from the others.`, { label: 'judge:' + (i + 1), phase: 'Judge', schema: JUDGE_SCHEMA })))

const synth = await agent(`${CONTEXT}\n\nTwo judges scored three designs for Quantum 5D chess:\n${JSON.stringify(judges.filter(Boolean), null, 1)}\n\nRead the designs (${R}/multiverse-design-*.md) and the research (${R}/multiverse-rules.md, -pieces.md, -engines.md). Write the FINAL, authoritative spec ${R}/multiverse-final.md: start from the winning design, graft the listed ideas, resolve every contradiction, and make every rule exact and implementable on the current core (verify against the code). Same sections as the designs (rules, setup/options, engine mapping, quantum rules, UI, at least 25 test scenarios with exact expected results), plus the player-facing documentation text (a level-3 heading and 6-12 bullets) and the rules() sentences. Return a 15-line summary.`, { label: 'synthesise', phase: 'Judge' })

phase('Implement')
const impl = await agent(`${CONTEXT}\n\nImplement the variant exactly as specified in ${R}/multiverse-final.md.\n- Replace the placeholder ${REPO}/src/variants/multiverse.js (default export defineVariant({...}), id 'multiverse', category 'dimensions').\n- Tests ${REPO}/tests/js/variants/multiverse.spec.js: every test scenario of the spec that can be expressed, plus setup, movement of every piece type along each axis, branching, travel to another timeline, the present, active timelines, submitting, limits, the win condition, and quantum interactions (split, roll, link, measure, solid/structure roll, game-end roll). Aim for 30+ tests.\n- Documentation snippet ${SP}/docs/multiverse.md (from the spec).\n- You may only create/edit: src/variants/multiverse.js, tests/js/variants/multiverse.spec.js (and extra helper modules src/variants/multiverse/*.js if the module gets large), ${SP}/docs/multiverse.md. Do not edit the core, the UI or other variants; if the core blocks you, use the hooks (generate/apply overrides) and report what the core should change.\n- Follow the style rules of IMPLEMENTING.md and make these pass: npx eslint (0 problems) on your files, node tools/check-line-length.mjs (no findings in your files), npx vitest run tests/js/variants/multiverse.spec.js, npx vitest run tests/js/variants/fuzz.spec.js -t multiverse (fast: a 60-ply random game in a few seconds).\nReturn a report: what you built, deviations from the spec and why, test count, performance numbers, anything the core or UI should change.`, { label: 'implement', phase: 'Implement' })

phase('UI')
const ui = await agent(`${CONTEXT}\n\nThe rules module ${REPO}/src/variants/multiverse.js is implemented (report below). Make the multiverse look and play great in the app UI.\nImplementer report:\n${impl}\n\nRead ${R}/multiverse-final.md (section UI), src/variantplay/components/VariantBoard.vue, VariantPiece.vue, src/variantplay/composables/useVariantGame.js, src/views/VariantGameView.vue.\nDo:\n- Make sure the multiverse layout is clear: timelines as rows, time as columns, a visible present, labels per board (timeline and time, whose move), the boards where the player must still move highlighted, arrows for time travel/branching (add generic support for layout.arrows [{ x1, y1, x2, y2, kind }] in VariantBoard if the layout provides them), focus on the present, zoom/pan working with many boards, the "Submit turn" action, and a status line that says how many boards still need a move. Keep additions generic (hooks and layout fields any variant could use) and small.\n- You may edit: src/variantplay/**, src/views/VariantGameView.vue, src/variants/multiverse.js (layout only), and add tests under tests/js/variants/. Do not change core rules.\n- Verify visually: build a throwaway harness in ${SP}/ui-harness (a tiny Vite config + HTML that mounts VariantBoard with multiverse states after several moves including a branch, with the piece sprite from src/board/pieceSprites.js), serve it, and take screenshots with Playwright (Chromium is at /opt/pw-browsers; PLAYWRIGHT_BROWSERS_PATH is set; never run "playwright install"). Look at the screenshots (Read the PNG files) and iterate until it looks clear at desktop and phone widths. Save the final screenshots to ${SP}/screens/multiverse-*.png.\n- Run npx eslint on changed files, node tools/check-line-length.mjs, npx vitest run tests/js/variants.\nReturn a report with the screenshot paths.`, { label: 'ui', phase: 'UI' })

phase('Verify')
const FIND_SCHEMA = {
  type: 'object',
  properties: { findings: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, severity: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['title', 'severity', 'evidence', 'fix'] } } },
  required: ['findings'],
}
const LENSES = [
  { key: 'rules', prompt: 'Rules fidelity: does the implementation follow multiverse-final.md exactly (setup, movement of every piece along every axis, travel to past boards branches correctly, travel to other timelines, the present, active timelines, turns and submit, limits, win/draw)? Compare with the real game research where the spec is silent.' },
  { key: 'quantum', prompt: 'Quantum consistency: splits/merges/measures across boards and timelines, rolls and links, the structure (solidExtra) staying classical, the game-end roll, the budget and world bound, deep random games with many splits: invariants must hold and nothing may throw; state size must stay bounded.' },
  { key: 'perf-ai-ui', prompt: 'Performance, the computer player and the UI: time per move generation/application with many timelines and 8 worlds; the computer must play legal, sensible multi-move turns and always submit; the layout must be correct and readable (every square drawn once, labels, arrows, present, focus); the texts (rules(), docs snippet, action labels) must match behaviour.' },
]
const verdicts = await parallel(LENSES.map((l) => () => agent(`${CONTEXT}\n\nYou are an adversarial verifier of ${REPO}/src/variants/multiverse.js (spec ${R}/multiverse-final.md; UI in src/variantplay and src/views/VariantGameView.vue). Lens: ${l.prompt}\nProve every finding by running code: write a temporary vitest file ${REPO}/tests/js/variants/probe-mv-${l.key}.spec.js, run it with npx vitest run <file>, and DELETE it afterwards. Do not edit any other file. Report only confirmed defects with evidence and a concrete fix.`, { label: 'verify:' + l.key, phase: 'Verify', schema: FIND_SCHEMA })))

phase('Fix')
const all = verdicts.filter(Boolean).flatMap((v) => v.findings)
log(all.length + ' confirmed findings')
const fixed = all.length ? await agent(`${CONTEXT}\n\nApply these confirmed findings for the multiverse variant (fix each one, add a regression test for each):\n${JSON.stringify(all, null, 1)}\n\nYou may edit src/variants/multiverse.js (and src/variants/multiverse/*), tests/js/variants/multiverse*.spec.js, ${SP}/docs/multiverse.md, src/variantplay/**, src/views/VariantGameView.vue. Then run npx eslint on changed files, node tools/check-line-length.mjs, npx vitest run tests/js/variants. Return a report per finding: fixed / not a defect (with reason).`, { label: 'fix', phase: 'Fix' }) : 'no findings'
return { research, designs, judges, synth, impl, ui, findings: all, fixed }
