export const meta = {
  name: 'variant-research',
  description: 'Research exact rules of 19 chess variants and design their quantum adaptation',
  phases: [{ title: 'Research', detail: 'one agent per variant group' }, { title: 'Critique', detail: 'adversarial check of each spec' }],
}

const SP = args.scratchpad
const GROUPS = [
  { ids: ['raumschach', 'trid'], brief: 'Raumschach (5x5x5 3D chess, Maack 1907: exact setup incl. unicorns, pawn movement in 3D, promotion) AND Star Trek Tri-Dimensional Chess (Bartmess "Federation Standard" rules: 3 main 4x4 levels + 4 attack boards 2x2). For Tri-D propose a SIMPLIFIED playable version with the 4 attack boards FIXED in their starting pins (no attack-board moves), and precise square coordinates, which squares exist, how pieces move between levels (projection rule), setup, promotion.' },
  { ids: ['multiverse'], brief: '5D Chess with Multiverse Time Travel. Research the real rules precisely (timelines, boards per turn, the present, moving through time and across timelines, branching, active timelines, checkmate). Then design a PLAYABLE SIMPLIFIED "5D-lite" that fits the engine: one move per ply, capture-the-king wins (no check), a small board (propose 5x5 or 8x8 with justification; smaller keeps the UI readable), bounded number of timelines (e.g. at most 5) and bounded history window, how a time-travel move is encoded as a square-based key, how squares are numbered (static integer encoding with caps), what the world object is, which timeline(s) are playable on a turn. The quantum layer (worlds of multiverses) sits on top.' },
  { ids: ['hyper4d'], brief: '4D chess on a 4x4x4x4 hypercube displayed as a 4x4 grid of 4x4 boards. Research existing 4D chess variants (e.g. 4D chess by Oliver Rowe? hyperchess, "4D Chess" by various authors, the 4x4x4x4 variants on chessvariants.com) and propose a clean variant: setup (which boards hold pieces), movement of rook/bishop/queen/king/knight/pawn in 4D (rook: 1 axis; bishop: 2 axes equal; queen/king: all 80 directions or rook+bishop only - choose and justify), pawn forward axes, promotion squares, no castling/en passant unless justified.' },
  { ids: ['kriegspiel', 'darkchess'], brief: 'Kriegspiel (umpire, what is announced: illegal attempts, captures with square, checks and direction, pawn tries; different rule sets e.g. ICC, Cincinnati) and Dark Chess / Fog of War (lichess/chess.com Fog of War: which squares are visible, capture-the-king, en passant visibility). In a quantum version with capture-the-king and no check: define exactly what each player sees (visibility over superposed pieces: a square is visible if some own piece might reach it?), what the umpire announces in Kriegspiel (move attempted is illegal in every world -> "try again" without spending the turn; announce capture squares; announce "king in danger"?), pass-and-play hand-over, and what the computer is allowed to know.' },
  { ids: ['chess960', 'koth', 'threecheck'], brief: 'Chess960 (Fischer Random: the 960 start positions, the standard numbering scheme 0-959 and how to derive the position from the number, castling rules in 960 incl. king/rook destination squares and required empty squares), King of the Hill (lichess rules: the four centre squares, win immediately when the king reaches one), Three-check (lichess rules: third check wins, how checks are counted, double check counts once). Quantum adaptation: capture-the-king, no check rules; define what "check" means per world for three-check (king attacked in that world after the move) and how the counter works with the game-end roll.' },
  { ids: ['atomic'], brief: 'Atomic chess (lichess rules): explosion on capture of all non-pawn pieces in the 8 surrounding squares plus the capturing piece and the captured piece; kings cannot capture; adjacent kings; win by exploding the enemy king; en passant explosion centre. Quantum adaptation with capture-the-king wins, ghosts in the blast radius (a ghost part in the radius is destroyed only in the worlds where it is there), no check rules.' },
  { ids: ['crazyhouse', 'bughouse'], brief: 'Crazyhouse (lichess rules: drops, pawns not on 1st/8th rank, promoted pieces revert to pawns when captured, drop anywhere empty) and Bughouse (4 players, 2 boards, teams, captured pieces go to the partner, drops). Bughouse must become TURN-BASED for pass & play/computer: propose a turn order over the four seats, team structure, how a win on one board ends the game. Quantum adaptation: hands may differ per world (a ghost captured only in some worlds); drops are rolled when not certain; which piece id is dropped.' },
  { ids: ['antichess', 'horde'], brief: 'Antichess / Losing chess (lichess rules: capturing is compulsory, king is an ordinary piece, promotion to king allowed, no castling, win by losing all pieces or being stalemated) and Horde (lichess setup: exact 36 white pawn squares incl. pawns on rank 1 that can double-step?, black normal army, white wins by checkmate - quantum: capture the black king; black wins by capturing all white pieces). Quantum adaptation of compulsory capture across worlds (a capture available in some worlds only), and of the win conditions via the game-end roll.' },
  { ids: ['hexagonal'], brief: 'Glinski hexagonal chess: 91 cells, the 11 files a-l (no j), rank numbering, cell colours (three shades), exact setup (incl. 3 bishops, 9 pawns), movement of each piece on hexes (rook 6 orthogonal directions, bishop 6 diagonal directions, queen, king 12 directions, knight 12 targets), pawn moves and captures, double step from starting cells, en passant, promotion cells, stalemate rule. Give axial/cube coordinate formulas mapping cells to (q, r) and a layout for flat-topped hexes (Glinski boards use flat-topped hexes with files vertical). Quantum adaptation (capture the king).' },
  { ids: ['fourplayer'], brief: 'Four-player chess (chess.com style: 14x14 board minus 3x3 corners, Red/Blue/Yellow/Green, setup of each army, pawn directions, promotion rank (e.g. 8th rank from own side in FFA vs centre), turn order, Free-for-all vs Teams, what happens to an eliminated player pieces). Quantum adaptation: capture the king eliminates that player; last player (or team) standing wins; points-based FFA optional - propose the simplest fair rule set for local play and the computer.' },
  { ids: ['capablanca', 'makruk'], brief: 'Capablanca chess (10x8, exact setup with archbishop and chancellor, castling rules - king moves 3 squares, pawn rules, promotion options) and Makruk (Thai chess: setup with pawns on 3rd rank, Khon/Met/Ma/Rua/Bia moves, promotion of Bia on 6th rank to Met, no double step, counting rules - propose a simplified draw rule). Quantum adaptation: which pieces are solid (Bia pawns, Khun king) and splittable.' },
  { ids: ['shogi'], brief: 'Shogi (Japanese chess): 9x9, full setup, all piece moves incl. promoted pieces (tokin, narikyo, narikei, narigin, dragon, horse), promotion zone rules (optional/compulsory promotion), drops (restrictions: nifu - two unpromoted pawns on a file, no drop where piece could never move, uchifuzume - pawn-drop mate: propose how to handle with capture-the-king), captured pieces change side and demote. Quantum adaptation: solid pieces (king, pawns?), splittable pieces, promotion per world, drops rolled when uncertain, glyphs (kanji for each piece and promoted form, pentagon piece shape pointing to the opponent).' },
  { ids: ['xiangqi'], brief: 'Xiangqi (Chinese chess): 9x10 intersections, river, palaces, full setup, moves of general, advisor, elephant (blocked eye, cannot cross river), horse (blocked leg), chariot, cannon (screen capture), soldier (sideways after river), flying general rule (generals may not face each other: with capture-the-king it becomes a capture?), perpetual check/chase rules (propose simplification), stalemate is a loss. Quantum adaptation: what is solid (general, soldiers?), splittable, how cannon screens interact with ghosts (a ghost screen exists only in some worlds - per world evaluation), glyphs (red and black characters differ: e.g. 帥/將, 仕/士, 相/象, 傌/馬, 俥/車, 炮/砲, 兵/卒), drawing the board on intersections.' },
]

const PROMPT = (g) => `You are researching chess variants for "Quantum Chess" 2.0, a Nextcloud app (repo at /home/user/Quantum_Chess). Read the architecture contract at ${SP}/CONTRACT.md first (it explains the generic quantum layer every variant plugs into), and skim /home/user/Quantum_Chess/docs/rules.md (the existing quantum rules the variants must share).

Your variant(s): ${g.ids.join(', ')}.
Brief: ${g.brief}

Do careful research. Use WebSearch/WebFetch if available (lichess.org variant pages, chessvariants.com, Wikipedia, official rule sets); otherwise rely on precise knowledge and say so. Be exact: coordinates of every start square, every move rule, every special case. Where sources disagree, pick one rule set, name it and justify.

For EACH variant id write a spec file ${SP}/research/<id>.md with these sections:
1. Sources (URLs or references) and the rule set chosen.
2. Classical rules, complete and exact: board/topology (coordinates, square naming, which cells exist), pieces and movement (as descriptors: leap/ride/hop/lame leaper vectors, oriented vectors, modes move/capture, regions), setup (every square), special moves, promotion, win/draw conditions, turn order.
3. Engine mapping for the contract: sides, teams, enemies, topology coordinates, pieceTypes with descriptors, which types are royal / solid / splittable, piece values for a computer player (centipawn-like), extraMoves, afterMove, worldResult, visibility (if any), options (if any).
4. Quantum adaptation: how the quantum rules (split/merge/measure, land=roll pass=link, solid roll, game-end roll, budget 8) interact with this variant's special rules; decide every ambiguous case explicitly; keep it simple, fair and explainable to players in a few sentences.
5. Player-facing rules text: 4 to 8 short bullet sentences in plain English for the in-app rules card (the quantum rules shared by all variants are explained elsewhere; only say what is special here).
6. UI layout: how to draw it (cell shape, how several boards are arranged, colours/shades, labels, glyphs for non-orthodox pieces: which characters/letters, shapes).
7. Test cases: at least 8 concrete, checkable scenarios (position described exactly + move + expected result), covering the special rules and at least 2 quantum interactions.

Return a short summary: files written, the rule set chosen, and any open design questions.`

const CRITIC = (id) => `You are an adversarial reviewer of a chess-variant spec for "Quantum Chess" 2.0. Read ${SP}/CONTRACT.md, then ${SP}/research/${id}.md. Check it against authoritative rules (use WebSearch/WebFetch if available, else precise knowledge): wrong setup squares, wrong movement, missing special cases, inconsistencies with the contract, ambiguous quantum rules, test cases whose expected result is wrong. Fix the file IN PLACE (edit ${SP}/research/${id}.md) so it becomes correct and unambiguous; append a section "8. Review notes" listing what you changed and why. Return a short list of the changes.`

// Resume support: args.skip lists variant ids whose research file already exists (they only get the critique);
// args.done lists ids whose spec already has "8. Review notes" (skipped completely).
const skip = new Set(args.skip ?? [])
const done = new Set(args.done ?? [])
const todo = GROUPS
  .map((g) => ({ ...g, ids: g.ids.filter((id) => !done.has(id)) }))
  .filter((g) => g.ids.length)
const results = await pipeline(
  todo,
  (g) => (g.ids.every((id) => skip.has(id))
    ? Promise.resolve('research present')
    : agent(PROMPT(g), { label: 'research:' + g.ids.join('+'), phase: 'Research' })),
  (summary, g) => parallel(g.ids.map((id) => () => agent(CRITIC(id), { label: 'critique:' + id, phase: 'Critique' }).then((c) => ({ id, critique: c })))).then((cs) => ({ ids: g.ids, summary, critiques: cs })),
)
return results.filter(Boolean)
