import { ZH as V } from './zh.mjs'
import { stateOf, show, outs, after, codes, newGame, handView, budget, ownPieceAt, splitsFrom, pieceLocations } from './lib.mjs'
const sq = (n) => V.topology.byName(n)
const hr = (t) => console.log('\n=== ' + t)
const hv = (s, side) => JSON.stringify(handView(s, side))
const res = (s) => JSON.stringify(s.result)

hr('Z1 capture goes to hand, colour changes (1.e4 d5 2.exd5 Qxd5 3.Nc3 Qa5?)')
let s = newGame(V)
for (const m of ['e2-e4', 'd7-d5', 'e4-d5', 'd8-d5']) s = after(V, s, m)
console.log('W hand', hv(s, 0), 'B hand', hv(s, 1), 'quiet', s.quiet)
console.log('white drops available:', codes(V, s).filter(c => c.includes('@')).length, codes(V, s).filter(c => c.startsWith('p@')).slice(0, 3))
console.log('p@e1 legal?', codes(V, s).includes('p@e1'), 'p@e8?', codes(V, s).includes('p@e8'), 'p@e7? (occupied)', codes(V, s).includes('p@e7'), 'p@e3', codes(V, s).includes('p@e3'))

hr('Z2 certain drop, fresh id, quiet reset')
s = stateOf(V, [[{ e1: '0:k', e8: '1:k' }, 1, [[0, 'n']]]], 0)
s = { ...s, quiet: 7 }
console.log(outs(V, s, 'n@f3'))
let d = after(V, s, 'n@f3')
console.log(show(V, d), 'quiet', d.quiet, 'hand', hv(d, 0))

hr('Z3 pawn drop ranks: W hand p; black pawn drop too')
s = stateOf(V, [[{ e1: '0:k', e8: '1:k' }, 1, [[0, 'p'], [1, 'p']]]], 0)
const c3 = codes(V, s)
console.log('p@a1', c3.includes('p@a1'), 'p@h8', c3.includes('p@h8'), 'p@a2', c3.includes('p@a2'), 'p@h7', c3.includes('p@h7'), 'count p drops', c3.filter(c => c.startsWith('p@')).length)
const s3b = { ...s, turn: 1 }
const c3b = codes(V, s3b)
console.log('black p@a1', c3b.includes('p@a1'), 'p@a8', c3b.includes('p@a8'), 'p@a2', c3b.includes('p@a2'), 'count', c3b.filter(c => c.startsWith('p@')).length)

hr('Z4 dropped pawn on 2nd rank double-steps, can be taken e.p.')
s = stateOf(V, [[{ e1: '0:k', e8: '1:k', e4: '1:p', a7: '1:p' }, 1, [[0, 'p']]]], 0)
s = after(V, s, 'p@d2')
s = after(V, s, 'a7-a6')
console.log('d2-d4 legal', codes(V, s).includes('d2-d4'), outs(V, s, 'd2-d4'))
s = after(V, s, 'd2-d4')
console.log('ep', JSON.stringify(s.worlds[0].b.x.ep), 'e4-d3 legal', codes(V, s).includes('e4-d3'))
s = after(V, s, 'e4-d3')
console.log(show(V, s), 'B hand', hv(s, 1))

hr('Z5 promoted piece reverts to pawn')
s = stateOf(V, [[{ a1: '0:k', e7: '0:p', h8: '1:k', a8: '1:r' }, 1]], 0)
console.log(codes(V, s).filter(c => c.startsWith('e7')))
s = after(V, s, 'e7-e8=q')
console.log(show(V, s))
console.log('queen moves', codes({ ...V }, { ...s, turn: 0 }).filter(c => c.startsWith('e8')).length)
s = after(V, s, 'a8-e8')
console.log(show(V, s), 'B hand', hv(s, 1))

hr('Z6 dropped rook cannot castle')
s = stateOf(V, [[{ e1: '0:k', h1: '0:r', e8: '1:k', a7: '1:p' }, 1, [[0, 'r']]]], 0, (b) => { b.x = { ep: -1, epVictim: -1, castle: [{ flag: 'K', side: 0, king: sq('e1'), rook: sq('h1'), kingTo: sq('g1'), rookTo: sq('f1') }] } })
console.log('O-O initially', codes(V, s).includes('O-O'))
s = after(V, s, 'h1-h5')
s = after(V, s, 'a7-a6')
s = after(V, s, 'r@h1')
s = after(V, s, 'a6-a5')
console.log(show(V, s))
console.log('O-O after dropping rook on h1', codes(V, s).includes('O-O'))
