import { ZH as V } from './zh.mjs'
import { stateOf, show, outs, after, codes, handView, budget, ownPieceAt, splitsFrom, pieceLocations } from './lib.mjs'
const sq = (n) => V.topology.byName(n)
const hr = (t) => console.log('\n=== ' + t)
const hv = (s, side) => JSON.stringify(handView(s, side).map(h => h.type + ':' + h.min + '-' + h.max))
hr('Z7 promoted queen split, then captured on one part: capturer gets a pawn (capture branch)')
let s = stateOf(V, [[{ a1: '0:k', d7: '0:p', h8: '1:k', a5: '1:r', h1: '1:b' }, 1]], 0)
s = after(V, s, 'd7-d8=q')
s = after(V, s, 'h8-h7')
s = after(V, s, 'd8-d5|d2')
console.log(show(V, s))
console.log(outs(V, s, 'a5-d5'))
const cap = after(V, s, 'a5-d5', 1)
console.log(show(V, cap), 'B hand', hv(cap, 1))
hr('Z8 dropped pawn on 7th rank promotes next move')
s = stateOf(V, [[{ a1: '0:k', h8: '1:k', a6: '1:p' }, 1, [[0, 'p']]]], 0)
s = after(V, s, 'p@c7'); s = after(V, s, 'a6-a5')
console.log(codes(V, s).filter(c => c.startsWith('c7')))
hr('Z9 drop between king and rook blocks castling in that world; castling with a ghost on f1 rolls')
s = stateOf(V, [[{ e1: '0:k', h1: '0:r', e8: '1:k' }, 1, [[1, 'n']]]], 1, (b) => { b.x = { ep: -1, epVictim: -1, castle: [{ flag: 'K', side: 0, king: sq('e1'), rook: sq('h1'), kingTo: sq('g1'), rookTo: sq('f1') }] } })
s = after(V, s, 'n@f1')
console.log('O-O legal after enemy drop on f1', codes(V, s).includes('O-O'), 'e1-f1 capture', outs(V, s, 'e1-f1'))
hr('Z10 king capture by a knight dropped next to it (drop then capture)')
s = stateOf(V, [[{ a1: '0:k', h8: '1:k', h7: '1:p', g7: '1:p' }, 1, [[0, 'n']]]], 0)
s = after(V, s, 'n@f7')
console.log('danger', 'black to move', s.turn)
s = after(V, s, 'a7' in {} ? 'x' : 'g7-g6')
console.log(outs(V, s, 'f7-h8'))
s = after(V, s, 'f7-h8')
console.log(JSON.stringify(s.result))
hr('Z11 drop from ghost-linked hand? — hands identical: checked in fuzz (handDiffStates 0)')
