import { V, visibility, names, newGame, applyOutcome, br, st, legalMoves, squareView, N, pieceLocations, royalDanger } from './proto.mjs'
let s8 = st([[{ a1: '0:r', e1: '0:k', e8: '1:k', a5: '1:n' }, 1], [{ a1: '0:r', e1: '0:k', e8: '1:k', h5: '1:n' }, 1]], 0)
let s = applyOutcome(V, s8, 'a1-a8', 0)
console.log('white vis after a1-a8', names(visibility(s, 0)).join(' '))
console.log('black h5-g7', JSON.stringify(br(s, 'h5-g7')))
s = applyOutcome(V, s, 'h5-g7', 0)
console.log('white vis', names(visibility(s, 0)).join(' '))
console.log('a8-e8', JSON.stringify(br(s, 'a8-e8')))
const w = applyOutcome(V, s, 'a8-e8', 1)
console.log('result', JSON.stringify(w.result))
const m = applyOutcome(V, s, 'a8-e8', 0)
console.log('miss locs', JSON.stringify(pieceLocations(m, 0).map(l => [N(l.sq), l.p])), JSON.stringify(pieceLocations(m, 3).map(l => [N(l.sq), l.p])))
// D9 pawn diag
let s9 = st([[{ e1: '0:k', e4: '0:p', e8: '1:k', d5: '1:n' }, 1], [{ e1: '0:k', e4: '0:p', e8: '1:k', b6: '1:n' }, 1]], 0)
console.log('D9 vis', names(visibility(s9, 0)).join(' '))
console.log('D9 e4-d5', JSON.stringify(br(s9, 'e4-d5')), 'e4-f5', JSON.stringify(br(s9, 'e4-f5')), 'e4-e5', JSON.stringify(br(s9, 'e4-e5')))
// D6 king into danger
let s6 = st([[{ e1: '0:k', h8: '1:k', d8: '1:r' }, 1]], 0)
console.log('D6 vis', names(visibility(s6, 0)).join(' '))
let s6b = applyOutcome(V, s6, 'e1-d1', 0)
console.log('D6 black vis', names(visibility(s6b, 1)).join(' '), JSON.stringify(br(s6b, 'd8-d1')))
console.log('D6 result', JSON.stringify(applyOutcome(V, s6b, 'd8-d1', 0).result))
// D5 castling
let s5 = st([[{ e1: '0:k', h1: '0:r', a8: '1:k', f8: '1:r' }, 1]], 0, { ep: -1, epVictim: -1, castle: [{ flag: 'K', side: 0, king: V.topology.byName('e1'), rook: V.topology.byName('h1'), kingTo: V.topology.byName('g1'), rookTo: V.topology.byName('f1') }] })
console.log('D5 moves', legalMoves(V, s5).map(m=>m.code).join(' '), 'vis', names(visibility(s5, 0)).join(' '))
const c = applyOutcome(V, s5, 'O-O', 0)
console.log('D5 after O-O white', JSON.stringify(squareView(c, V.topology.byName('g1'))), JSON.stringify(squareView(c, V.topology.byName('f1'))), 'black vis', names(visibility(c, 1)).join(' '))
