import { V, visibility, names, newGame, applyOutcome, br, st, legalMoves, squareView, N, pieceLocations, royalDanger, candidateMoves, checkInfo, pawnTries, branches, splitTargets, ownOnly } from './proto.mjs'
let s = newGame(V)
const c = candidateMoves(s)
console.log('K1 cands', c.length, c.filter(m => m.kind === 'try').map(m => m.code).join(' '))
console.log('K1 illegal among cands', c.filter(m => !branches(V, s, m.code)).map(m=>m.code).join(' '))
console.log('K1 tries', pawnTries(s))
// K2 No
let s2 = st([[{ e1: '0:k', e2: '0:p', e8: '1:k', e3: '1:n' }, 1]], 0)
console.log('K2 cands', candidateMoves(s2).map(m=>m.code).join(' '))
for (const code of ['e2-e4', 'e2-e3', 'e2-d3', 'e2-f3', 'e1-d1']) console.log('K2', code, JSON.stringify(br(s2, code)))
console.log('K2 tries', pawnTries(s2))
// K3 capture + check long diagonal
let s3 = st([[{ e1: '0:k', d1: '0:q', e8: '1:k', d7: '1:p' }, 1]], 0)
console.log('K3 Qxd7', JSON.stringify(br(s3, 'd1-d7')))
let s3b = applyOutcome(V, s3, 'd1-d7', 0)
console.log('K3 check', JSON.stringify(checkInfo(s3b)), 'tries black', pawnTries(s3b))
let s3c = applyOutcome(V, s3b, 'e8-d7', 0)
console.log('K3 Kxd7', JSON.stringify(s3c.history.at(-1).captures), 'check on white', JSON.stringify(checkInfo(s3c)))
// K4 double check file+knight and short diagonal
let s4 = st([[{ a1: '0:k', e1: '0:r', f6: '0:n', e8: '1:k' }, 1]], 1)
console.log('K4 check', JSON.stringify(checkInfo(s4)))
let s4b = st([[{ a1: '0:k', h5: '0:b', e8: '1:k' }, 1]], 1)
console.log('K4b check', JSON.stringify(checkInfo(s4b)))
let s4c = st([[{ a1: '0:k', a4: '0:b', e8: '1:k' }, 1]], 1)
console.log('K4c check', JSON.stringify(checkInfo(s4c)))
let s4d = st([[{ a1: '0:k', h8: '0:r', e8: '1:k', d7: '0:p' }, 1]], 1)
console.log('K4d check', JSON.stringify(checkInfo(s4d)))
// K5 tries
let s5 = st([[{ e1: '0:k', e4: '0:p', d4: '0:p', e8: '1:k', d5: '1:p', f5: '1:n', g7: '0:p', h8: '1:r' }, 1]], 0)
console.log('K5 tries', pawnTries(s5), legalMoves(V, s5).filter(m => /^(e4|d4|g7)/.test(m.code)).map(m => m.code).join(' '))
