import { THREECHECK as V } from './proto.mjs'
import { stateOf, show, outs, after, codes, newGame } from './lib.mjs'
const hr = (t) => console.log('\n=== ' + t)
const res = (s) => JSON.stringify(s.result)
const C = (c) => (b) => { b.x.checks = c.slice() }
const chk = (s) => s.worlds.map(({ b, w }) => b.x.checks.join(':') + '@' + (w / 16777216).toFixed(3)).join(' ')
hr('C1 1.e4 e5 2.Bc4 Nc6 3.Bxf7 check')
let s = newGame(V)
for (const m of ['e2-e4', 'e7-e5', 'f1-c4', 'b8-c6', 'c4-f7']) s = after(V, s, m)
console.log(chk(s), res(s))
hr('C2 double check counts once: W Kg1 Rh1? use Re1 + Bd3?: W Ke1? set: W Kh1, Re2, Nd6? B Ke8; Nd6-? ... discovered: W Re1, Nf6?? ')
// rook e1, knight e5 (blocks), black king e8; knight e5-d7?? d7 not check. e5-f7 no. use Nc6? knight e5 -> d7? knight on d7 attacks f8,f6,b8,b6,c5,e5 no. e5->f6: knight f6 attacks e8 (yes: f6->e8 is (-1,+2)). So Ne5-f6 = double check (rook e1 + knight f6)
s = stateOf(V, [[{ h1: '0:k', e1: '0:r', e4: '0:n', e8: '1:k' }, 1]], 0, C([0, 0]))
const d = after(V, s, 'e4-f6'); console.log(chk(d), res(d))
hr('C3 king approach is not a check: W Ke6? Kd6->e7?? use W Kd5-d6, black Kd8 (adjacent after move)')
s = stateOf(V, [[{ d5: '0:k', d8: '1:k' }, 1]], 0, C([2, 0]))
const k3 = after(V, s, 'd5-d6'); console.log(chk(k3), res(k3))
hr('C4 third check wins: W has 2, Qd1-d7?? W Qd1, K a1, B Ke8: Qd1-d7? adjacent: queen check yes')
s = stateOf(V, [[{ a1: '0:k', d1: '0:q', h8: '1:k' }, 1]], 0, C([2, 1]))
const c4 = after(V, s, 'd1-d8'); console.log(chk(c4), res(c4))
hr('C5 quantum split into check: W Kg1 Bf1; B Ke8. split f1-b5|d3')
s = stateOf(V, [[{ g1: '0:k', f1: '0:b', e8: '1:k' }, 1]], 0, C([0, 0]))
console.log(outs(V, s, 'f1-b5|d3'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'f1-b5|d3', i); console.log(i, chk(a), show(V, a)) }
hr('C6 quantum ghost part gives check: W queen 50% d1 / 50% d3; Qd1-h5 (f7 empty)')
s = stateOf(V, [[{ g1: '0:k', d1: '0:q', e8: '1:k' }, 1], [{ g1: '0:k', d3: '0:q', e8: '1:k' }, 1]], 0, C([0, 0]))
console.log(outs(V, s, 'd1-h5'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'd1-h5', i); console.log(i, chk(a), show(V, a)) }
hr('C7 quantum blocker: W Ra1-e1 with black knight 50% e5 / 50% c6; B Ke8')
s = stateOf(V, [[{ g1: '0:k', a1: '0:r', e5: '1:n', e8: '1:k' }, 1], [{ g1: '0:k', a1: '0:r', c6: '1:n', e8: '1:k' }, 1]], 0, C([0, 0]))
console.log(outs(V, s, 'a1-e1'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'a1-e1', i); console.log(i, chk(a), show(V, a)) }
hr('C8 third check by a ghost: W has 2; queen 50% d1 / 50% d3; Qd1-h5 -> 50% win, 50% continue')
s = stateOf(V, [[{ g1: '0:k', d1: '0:q', e8: '1:k' }, 1], [{ g1: '0:k', d3: '0:q', e8: '1:k' }, 1]], 0, C([2, 0]))
console.log(outs(V, s, 'd1-h5'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'd1-h5', i); console.log(i, chk(a), res(a)) }
hr('C9 castling gives check: W Ke1 Rh1, B Kf8 -> O-O, rook f1 checks')
s = stateOf(V, [[{ e1: '0:k', h1: '0:r', f8: '1:k' }, 1]], 0, (b) => { b.x.checks = [0, 0]; b.x.castle = [{ flag: 'K', side: 0, king: V.topology.byName('e1'), rook: V.topology.byName('h1'), kingTo: V.topology.byName('g1'), rookTo: V.topology.byName('f1') }] })
const c9 = after(V, s, 'O-O'); console.log(chk(c9), show(V, c9))
hr('C10 persistent: Black left king in check; White plays unrelated a2-a3 -> counts again')
s = stateOf(V, [[{ g1: '0:k', b5: '0:b', a2: '0:p', e8: '1:k' }, 1]], 0, C([1, 0]))
const c10 = after(V, s, 'a2-a3'); console.log(chk(c10))
hr('C11 promotion check: W pawn e7-e8=q? black king h8: e8 queen checks h8 along rank (f8,g8 empty)')
s = stateOf(V, [[{ a1: '0:k', e7: '0:p', h8: '1:k' }, 1]], 0, C([0, 0]))
console.log(codes(V, s).filter(c => c.startsWith('e7')))
const c11 = after(V, s, 'e7-e8=q'); console.log(chk(c11)); const c11n = after(V, s, 'e7-e8=n'); console.log('knight promo', chk(c11n))
hr('C12 black counter: black gives check')
s = stateOf(V, [[{ e1: '0:k', a8: '1:r', h8: '1:k' }, 1]], 1, C([0, 0]))
const c12 = after(V, s, 'a8-a1'); console.log(chk(c12))
hr('C13 measure: no check counted even though king already attacked')
s = stateOf(V, [[{ g1: '0:k', b5: '0:b', a2: '0:p', e8: '1:k', c1: '0:n' }, 1], [{ g1: '0:k', b5: '0:b', a2: '0:p', e8: '1:k', h3: '0:n' }, 1]], 0, C([1, 0]))
console.log(outs(V, s, '?c1'))
