import { CHESS960 as V } from './proto.mjs'
import { stateOf, withCastle, show, outs, after, codes, newGame, legalMoves } from './lib.mjs'
const hr = (t) => console.log('\n=== ' + t)
hr('setup 0, 518, 959')
for (const n of [0, 518, 959]) { const s = newGame(V, { position: n }); console.log(n, show(V, s)[0]) }
hr('T1 king stays: K g1, R h1, R a1, f1 empty; black Ke8')
let s = stateOf(V, [[{ a1: '0:r', g1: '0:k', h1: '0:r', e8: '1:k' }, 1]], 0, withCastle(V))
console.log(codes(V, s).filter(c => c.startsWith('O') || c.startsWith('g1')))
console.log(legalMoves(V, s).filter(m=>m.kind==='castle').map(m => m.code + ' to=' + V.topology.names[m.to]))
console.log(outs(V, s, 'O-O'), show(V, after(V, s, 'O-O')))
console.log(outs(V, s, 'O-O-O'), show(V, after(V, s, 'O-O-O')))
hr('T2 king b1 one step: R a1 K b1 R h1; O-O-O and b1-c1 both exist')
s = stateOf(V, [[{ a1: '0:r', b1: '0:k', h1: '0:r', e8: '1:k' }, 1]], 0, withCastle(V))
console.log(legalMoves(V, s).filter(m => m.from === V.topology.byName('b1')).map(m => m.code + ' to=' + V.topology.names[m.to]))
console.log(show(V, after(V, s, 'O-O-O')), show(V, after(V, s, 'O-O')))
hr('T3 transposition: K f1 R g1 (short), R a1; O-O -> K g1 R f1')
s = stateOf(V, [[{ a1: '0:r', f1: '0:k', g1: '0:r', e8: '1:k' }, 1]], 0, withCastle(V))
console.log(show(V, after(V, s, 'O-O')))
hr('T4 rook stays: R d1 K e1 R h1 ... O-O-O needs c1 empty: K->c1 R stays d1')
s = stateOf(V, [[{ d1: '0:r', e1: '0:k', h1: '0:r', e8: '1:k' }, 1]], 0, withCastle(V))
console.log(show(V, after(V, s, 'O-O-O')))
hr('T5 blocked: SP 518-like K e1 R a1 N b1 -> no O-O-O (b1 is between rook and its target d1)')
s = stateOf(V, [[{ a1: '0:r', b1: '0:n', e1: '0:k', h1: '0:r', e8: '1:k' }, 1]], 0, withCastle(V))
console.log(codes(V, s).filter(c => c.startsWith('O')))
hr('T5b SP0 start: BBQNNRKR, after clearing? O-O needs f1 empty (other rook) -> none')
s = newGame(V, { position: 0 })
console.log(codes(V, s).filter(c => c.startsWith('O')))
hr('T6 king path blocked by piece beyond rook: K b1 R c1? (c1 rook is long? no: rook must be left) -> K c1? test K d1 R c1 long: K->c1(rook sq) R->d1(king sq)')
s = stateOf(V, [[{ c1: '0:r', d1: '0:k', h1: '0:r', e8: '1:k' }, 1]], 0, withCastle(V))
console.log(legalMoves(V, s).filter(m=>m.kind==='castle').map(m => m.code + ' to=' + V.topology.names[m.to]), show(V, after(V, s, 'O-O-O')))
hr('T7 quantum: ghost black knight 50% f1?? use white K e1 R h1, black knight 50% g1 / 50% h3')
s = stateOf(V, [[{ e1: '0:k', h1: '0:r', a1: '0:r', e8: '1:k', g1: '1:n' }, 1], [{ e1: '0:k', h1: '0:r', a1: '0:r', e8: '1:k', h3: '1:n' }, 1]], 0, withCastle(V))
console.log(outs(V, s, 'O-O'))
for (let i = 0; i < 2; i++) console.log(i, show(V, after(V, s, 'O-O', i)))
hr('T8 quantum rights differ: rook h1-h5 passes ghost black knight 50% h3 / 50% a6; then O-O')
s = stateOf(V, [[{ e1: '0:k', h1: '0:r', a1: '0:r', e8: '1:k', h3: '1:n' }, 1], [{ e1: '0:k', h1: '0:r', a1: '0:r', e8: '1:k', a6: '1:n' }, 1]], 0, withCastle(V))
console.log('h1-h5', outs(V, s, 'h1-h5'))
let s2 = after(V, s, 'h1-h5'); console.log(show(V, s2))
s2 = after(V, s2, 'e8-d8'); console.log(show(V, s2))
console.log('O-O', outs(V, s2, 'O-O'))
