import { KOTH as V } from './proto.mjs'
import { stateOf, show, outs, after, codes, newGame } from './lib.mjs'
const hr = (t) => console.log('\n=== ' + t)
const res = (s) => JSON.stringify(s.result)
hr('K1 Kd3-d4 free hill')
let s = stateOf(V, [[{ d3: '0:k', h8: '1:k' }, 1]])
console.log(outs(V, s, 'd3-d4'), res(after(V, s, 'd3-d4')))
hr('K2 e4 attacked by black pawn d5: Ke3-e4 illegal, Ke3-d4 legal? (d5 pawn attacks c4,e4)')
s = stateOf(V, [[{ e3: '0:k', d5: '1:p', h8: '1:k' }, 1]])
console.log(codes(V, s).filter(c => c.startsWith('e3')))
hr('K3 Kd3xd4 capturing undefended knight wins; defended by pawn e5 illegal')
s = stateOf(V, [[{ d3: '0:k', d4: '1:n', h8: '1:k' }, 1]])
console.log(outs(V, s, 'd3-d4'), res(after(V, s, 'd3-d4')))
s = stateOf(V, [[{ d3: '0:k', d4: '1:n', e5: '1:p', h8: '1:k' }, 1]])
console.log(codes(V, s).filter(c => c.startsWith('d3')))
hr('K4 x-ray: black rook d8, white king d3 (attacked already); d3-d4 stays on file -> illegal; d3-e4 legal')
s = stateOf(V, [[{ d3: '0:k', d8: '1:r', h8: '1:k' }, 1]])
console.log(codes(V, s).filter(c => c.startsWith('d3')))
hr('K5 quantum: black bishop 50% b6 (hits d4 via c5) / 50% a5: Kd3-d4')
s = stateOf(V, [[{ d3: '0:k', b6: '1:b', h8: '1:k' }, 1], [{ d3: '0:k', a5: '1:b', h8: '1:k' }, 1]])
console.log(outs(V, s, 'd3-d4'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'd3-d4', i); console.log(i, res(a), show(V, a)) }
hr('K6 quantum: black knight ghost 50% on d4 / 50% on a8 (not attacking d4): Kd3-d4')
s = stateOf(V, [[{ d3: '0:k', d4: '1:n', h8: '1:k' }, 1], [{ d3: '0:k', a8: '1:n', h8: '1:k' }, 1]])
console.log(outs(V, s, 'd3-d4'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'd3-d4', i); console.log(i, res(a)) }
hr('K7 enemy king covers e5: white Kf4, black Kf6; f4-e5 illegal, f4-e4 wins')
s = stateOf(V, [[{ f4: '0:k', f6: '1:k' }, 1]])
console.log(codes(V, s).filter(c => c.startsWith('f4')), res(after(V, s, 'f4-e4')))
hr('K8 black wins on the hill: black Ke6-d5, white Ka1')
s = stateOf(V, [[{ a1: '0:k', e6: '1:k' }, 1]], 1)
console.log(outs(V, s, 'e6-d5'), res(after(V, s, 'e6-d5')))
hr('K9 capture the king still wins: white Qd1xd8 king')
s = stateOf(V, [[{ a1: '0:k', d1: '0:q', d8: '1:k' }, 1]])
console.log(res(after(V, s, 'd1-d8')))
hr('K10 quantum: blocker ghost: black rook d8 behind a white-irrelevant black knight 50% d6 / 50% b8: Kd3-d4 (rook hits d4 only if d6 empty... d5,d6,d7)')
s = stateOf(V, [[{ c3: '0:k', d8: '1:r', d6: '1:n', h8: '1:k' }, 1], [{ c3: '0:k', d8: '1:r', b8: '1:n', h8: '1:k' }, 1]])
console.log(outs(V, s, 'c3-d4'))
for (let i = 0; i < 2; i++) { const a = after(V, s, 'c3-d4', i); console.log(i, res(a), show(V, a)) }
hr('K11 start: 20 moves, no result')
s = newGame(V); console.log(codes(V, s).length, res(s))
