const Chess = require('../5dsrc/package/dist/5d-chess.js')
const c = new Chess()
const tryDo = (label, f) => { try { const r = f(); console.log(label, 'OK', r === undefined ? '' : JSON.stringify(r)) } catch (e) { console.log(label, 'ERR', e.message.split('\n')[0]) } }
tryDo('w Nf3', () => c.move('Nf3')); tryDo('submit', () => c.submit())
tryDo('b Nf6', () => c.move('Nf6')); tryDo('submit', () => c.submit())
console.log('submittable before any move:', c.submittable())
tryDo('w travel', () => c.move('(0T2)Nf3>>(0T1)f5'))
console.log('submittable after active branch:', c.submittable())
tryDo('submit', () => c.submit())
console.log('black moves available (present only):', c.moves('notation_short').split('\n').slice(0,6).join(' | '))
tryDo('b move on L1', () => c.move('(1T1)e6'))
console.log('submittable after moving only on L1 (L0 T2b untouched):', c.submittable())
tryDo('submit', () => c.submit())
console.log('white present moves sample:', c.moves('notation_short').split('\n').slice(0,4).join(' | '))
c.print()
