import { CAPA as V } from './proto.mjs'
import { stateOf, withCastle, show, outs, after, codes, newGame, legalMoves } from '../c960/lib.mjs'
import { splitsFrom, legalMoves as LM, budget } from '/home/user/Quantum_Chess/src/variants/core/quantum.js'
const hr = (t) => console.log('\n=== ' + t)
const sq = (n) => V.topology.byName(n)
hr('C1 setup')
let s = newGame(V, {})
console.log(show(V, s)[0])
const lm = legalMoves(V, s)
console.log('moves', lm.length, lm.map((m) => m.code).join(' '))
hr('C2 archbishop / chancellor from e4 on empty board (plus kings a1/j8)')
s = stateOf(V, [[{ e4: '0:a', a1: '0:k', j8: '1:k' }, 1]])
console.log('A e4', codes(V, s).filter((c) => c.startsWith('e4-')).length, codes(V, s).filter((c) => c.startsWith('e4-')).join(' '))
s = stateOf(V, [[{ e4: '0:c', a1: '0:k', j8: '1:k' }, 1]])
console.log('C e4', codes(V, s).filter((c) => c.startsWith('e4-')).length, codes(V, s).filter((c) => c.startsWith('e4-')).join(' '))
s = stateOf(V, [[{ e4: '0:q', a1: '0:k', j8: '1:k' }, 1]])
console.log('Q e4', codes(V, s).filter((c) => c.startsWith('e4-')).length)
hr('C3 castling both ways')
s = stateOf(V, [[{ a1: '0:r', f1: '0:k', j1: '0:r', f8: '1:k' }, 1]], 0, withCastle(V))
console.log(legalMoves(V, s).filter((m) => m.code.startsWith('O')).map((m) => m.code))
console.log('O-O', outs(V, s, 'O-O'), show(V, after(V, s, 'O-O')))
console.log('O-O-O', outs(V, s, 'O-O-O'), show(V, after(V, s, 'O-O-O')))
hr('C4 queenside blocked by Nb1; kingside blocked by Bg1; black castles')
s = stateOf(V, [[{ a1: '0:r', b1: '0:n', f1: '0:k', j1: '0:r', f8: '1:k' }, 1]], 0, withCastle(V))
console.log(codes(V, s).filter((c) => c.startsWith('O')))
s = stateOf(V, [[{ a1: '0:r', g1: '0:b', f1: '0:k', j1: '0:r', f8: '1:k' }, 1]], 0, withCastle(V))
console.log(codes(V, s).filter((c) => c.startsWith('O')))
s = stateOf(V, [[{ f1: '0:k', a8: '1:r', f8: '1:k', j8: '1:r' }, 1]], 1, withCastle(V))
console.log('black', show(V, after(V, s, 'O-O')), show(V, after(V, s, 'O-O-O')))
hr('C4b castling into/through attack allowed: black rook on h8 attacks h1, i1')
s = stateOf(V, [[{ a1: '0:r', f1: '0:k', j1: '0:r', f8: '1:k', h8: '1:r', i8: '1:c' }, 1]], 0, withCastle(V))
console.log(codes(V, s).filter((c) => c.startsWith('O')))
hr('C5 promotion choices')
s = stateOf(V, [[{ e7: '0:p', a1: '0:k', j8: '1:k', d8: '1:n' }, 1]])
console.log(codes(V, s).filter((c) => c.startsWith('e7')))
hr('C6 double step and en passant on j-file')
s = stateOf(V, [[{ j2: '0:p', i4: '1:p', a1: '0:k', a8: '1:k' }, 1]])
console.log(codes(V, s).filter((c) => c.startsWith('j2')))
let s2 = after(V, s, 'j2-j4'); console.log(show(V, s2)); console.log(codes(V, s2).filter((c) => c.startsWith('i4')))
console.log(show(V, after(V, s2, 'i4-j3')))
hr('C7 quantum: own chancellor ghost 50% h1 / 50% h3 blocks O-O half the time')
s = stateOf(V, [[{ a1: '0:r', f1: '0:k', j1: '0:r', h1: '0:c', f8: '1:k' }, 1], [{ a1: '0:r', f1: '0:k', j1: '0:r', h3: '0:c', f8: '1:k' }, 1]], 0, withCastle(V))
console.log('O-O', outs(V, s, 'O-O'))
for (let i = 0; i < 2; i++) console.log(i, show(V, after(V, s, 'O-O', i)))
console.log('O-O-O', outs(V, s, 'O-O-O'))
hr('C8 quantum: archbishop split with a knight leap and a bishop slide; path blocked in one world')
s = stateOf(V, [[{ c1: '0:a', f1: '0:k', f8: '1:k', e3: '1:n' }, 1], [{ c1: '0:a', f1: '0:k', f8: '1:k', h6: '1:n' }, 1]], 0)
console.log(splitsFrom(V, s, sq('c1')).slice(0, 60).join(' '))
console.log('split c1-d3|g5', outs(V, s, 'c1-d3|g5'))
console.log(show(V, after(V, s, 'c1-d3|g5')))
hr('C9 quantum: chancellor knight jump over a ghost is certain; slide past ghost links')
s = stateOf(V, [[{ e4: '0:c', a1: '0:k', j8: '1:k', e5: '1:n' }, 1], [{ e4: '0:c', a1: '0:k', j8: '1:k', g5: '1:n' }, 1]], 0)
console.log('e4-f6', outs(V, s, 'e4-f6'))
console.log('e4-e7', outs(V, s, 'e4-e7'), show(V, after(V, s, 'e4-e7')))
console.log('e4-e5', outs(V, s, 'e4-e5'))
hr('C10 castling rights after split of j1 rook')
s = stateOf(V, [[{ a1: '0:r', f1: '0:k', j1: '0:r', f8: '1:k' }, 1]], 0, withCastle(V))
s2 = after(V, s, 'j1-j3|j5'); console.log(show(V, s2)); s2 = after(V, s2, 'f8-e8'); console.log('O-O', outs(V, s2, 'O-O'), 'O-O-O', outs(V, s2, 'O-O-O'))
hr('C11 i2 pawn undefended in the start position; black Ai? ... check a sample: 1.Ci3? ')
