import { MAKRUK as V, countInfo } from './proto.mjs'
import { show, outs, after, codes, newGame, legalMoves } from '../c960/lib.mjs'
import { STATE_VERSION, T, applyOutcome, splitsFrom } from '/home/user/Quantum_Chess/src/variants/core/quantum.js'
import { worldFrom } from '/home/user/Quantum_Chess/src/variants/core/world.js'
function stateOf(V, worlds, turn = 0, quiet = 0) {
  const total = worlds.reduce((a, [, w]) => a + w, 0); let rest = T
  const list = worlds.map(([pl, rel], i) => { const b = worldFrom(V, pl, {}); const w = i === worlds.length - 1 ? rest : Math.floor((T * rel) / total); rest -= w; return { b, w } })
  return { v: STATE_VERSION, variant: V.id, options: {}, worlds: list, turn, ply: 0, quiet, result: null, history: [] }
}
const hr = (t) => console.log('\n=== ' + t)
hr('M1 setup')
let s = newGame(V, {})
console.log(show(V, s)[0])
console.log('moves', legalMoves(V, s).length, legalMoves(V, s).map((m) => m.code).join(' '))
hr('M2 khon white e4, black e5 (kings a1 h8)')
s = stateOf(V, [[{ e4: '0:s', a1: '0:k', h8: '1:k' }, 1]])
console.log(codes(V, s).filter((c) => c.startsWith('e4-')).join(' '))
s = stateOf(V, [[{ e5: '1:s', a1: '0:k', h8: '1:k' }, 1]], 1)
console.log(codes(V, s).filter((c) => c.startsWith('e5-')).join(' '))
s = stateOf(V, [[{ d4: '0:m', a1: '0:k', h8: '1:k' }, 1]])
console.log('met', codes(V, s).filter((c) => c.startsWith('d4-')).join(' '))
hr('M3 no double step; promotion')
s = stateOf(V, [[{ e3: '0:p', c5: '0:p', b6: '1:n', a1: '0:k', h8: '1:k' }, 1]])
console.log(codes(V, s).filter((c) => /^(e3|c5)/.test(c)))
let s2 = after(V, s, 'c5-c6=+p'); console.log(show(V, s2))
s2 = after(V, s2, 'h8-g8'); console.log(codes(V, s2).filter((c) => c.startsWith('c6')))
s = stateOf(V, [[{ c5: '0:p', b6: '1:n', a1: '0:k', h8: '1:k' }, 1]])
console.log(show(V, after(V, s, 'c5-b6=+p')))
s = stateOf(V, [[{ d4: '1:p', e3: '0:n', a1: '0:k', h8: '1:k' }, 1]], 1)
console.log('black promo', codes(V, s).filter((c) => c.startsWith('d4')))
hr('M4 quantum: bia push onto ghost ma -> roll, promotion only when moved')
s = stateOf(V, [[{ c5: '0:p', c6: '1:n', a1: '0:k', h8: '1:k' }, 1], [{ c5: '0:p', a6: '1:n', a1: '0:k', h8: '1:k' }, 1]])
console.log(outs(V, s, 'c5-c6=+p'))
for (let i = 0; i < 2; i++) console.log(i, show(V, after(V, s, 'c5-c6=+p', i)))
hr('M5 quantum: met split and promoted bia split')
s = stateOf(V, [[{ d4: '0:m', f6: '0:+p', a1: '0:k', h8: '1:k' }, 1]])
console.log(splitsFrom(V, s, V.topology.byName('d4')).map((x) => x.code ?? JSON.stringify(x)).join(' '))
console.log(show(V, after(V, s, 'd4-c5|e5')))
console.log(splitsFrom(V, s, V.topology.byName('f6')).map((x) => x.code ?? JSON.stringify(x)).join(' '))
hr('M6 bia not splittable, khun not splittable')
s = stateOf(V, [[{ d3: '0:p', a1: '0:k', h8: '1:k' }, 1]])
console.log(splitsFrom(V, s, V.topology.byName('d3')), splitsFrom(V, s, V.topology.byName('a1')))
hr('M7 board count: 64 moves each without capture (quiet 127 -> 128)')
s = stateOf(V, [[{ a1: '0:k', b2: '0:r', h8: '1:k', g7: '1:n' }, 1]], 0, 127)
console.log(countInfo(V, s)); s2 = after(V, s, 'b2-b3'); console.log(s2.result, s2.quiet)
s = stateOf(V, [[{ a1: '0:k', b2: '0:r', h8: '1:k', g7: '1:n', c3: '0:p' }, 1]], 0, 127)
s2 = after(V, s, 'c3-c4'); console.log('bia move resets', s2.result, s2.quiet)
hr('M8 piece honour: KRR vs K: allowance 8-4+1=5 moves')
s = stateOf(V, [[{ a1: '0:k', b2: '0:r', c3: '0:r', h8: '1:k', g8: '1:n' }, 1]], 0, 30)
s2 = after(V, s, 'b2-b8'); console.log(s2.result, 'capture', s2.quiet, countInfo(V, s2))
let st = s2
const plies = ['h8-h7', 'c3-c4', 'h7-h6', 'c4-c5', 'h6-h7', 'c5-c6', 'h7-h6', 'c6-c5', 'h6-h7', 'c5-c4']
for (const p of plies) { st = after(V, st, p); console.log(p, st.quiet, JSON.stringify(countInfo(V, st)), st.result) ; if (st.result) break }
hr('M8b capture on the 5th move wins')
st = s2
for (const p of ['h8-h7', 'c3-c4', 'h7-h6', 'c4-c5', 'h6-h7', 'c5-c6', 'h7-h6', 'b8-b7']) st = after(V, st, p)
console.log(countInfo(V, st), show(V, st))
st = after(V, st, 'h6-h5'); console.log(countInfo(V, st)); st = after(V, st, 'c6-h6'); console.log('c6-h6?', st.result)
hr('M9 limits table')
const L = (pl) => { const x = countInfo(V, stateOf(V, [[pl, 1]], 1)); return x.allow + ' limit ' + x.limit }
console.log('KR vs K', L({ a1: '0:k', b2: '0:r', h8: '1:k' }))
console.log('K S S vs K', L({ a1: '0:k', b2: '0:s', c2: '0:s', h8: '1:k' }))
console.log('K N N vs K', L({ a1: '0:k', b2: '0:n', c2: '0:n', h8: '1:k' }))
console.log('K S M vs K', L({ a1: '0:k', b2: '0:s', c2: '0:m', h8: '1:k' }))
console.log('K N M +p vs K', L({ a1: '0:k', b2: '0:n', c2: '0:m', d2: '0:+p', h8: '1:k' }))
console.log('K R S S N vs K', L({ a1: '0:k', b2: '0:r', c2: '0:s', d2: '0:s', e2: '0:n', h8: '1:k' }))
console.log('K M vs K', L({ a1: '0:k', b2: '0:m', h8: '1:k' }))
hr('M10 bare kings')
s = stateOf(V, [[{ a1: '0:k', b2: '0:r', h8: '1:k', h7: '1:m' }, 1]], 1)
console.log('rook captured by ... ', outs(V, stateOf(V, [[{ a1: '0:k', b2: '1:m', h8: '1:k' }, 1]], 0), 'a1-b2'))
s2 = after(V, stateOf(V, [[{ a1: '0:k', b2: '1:m', h8: '1:k' }, 1]], 0), 'a1-b2'); console.log(s2.result)
s2 = after(V, stateOf(V, [[{ a1: '0:k', b2: '1:m', c3: '1:k' }, 1]], 0), 'a1-b2'); console.log('adjacent', s2.result, s2.turn)
hr('M11 quantum: capture of a ghost ma part -> bare only in capture branch')
s = stateOf(V, [[{ a1: '0:k', b1: '0:r', c1: '0:r', h8: '1:k', b6: '1:n' }, 1], [{ a1: '0:k', b1: '0:r', c1: '0:r', h8: '1:k', f6: '1:n' }, 1]], 0, 20)
console.log(outs(V, s, 'b1-b6'))
for (let i = 0; i < 2; i++) { const x = after(V, s, 'b1-b6', i); console.log(i, x.quiet, JSON.stringify(countInfo(V, x)), show(V, x)) }
hr('M12 no stalemate: lone khun a8 with only moves into attack must move')
s = stateOf(V, [[{ a8: '1:k', c7: '0:r', b1: '0:r', h1: '0:k' }, 1]], 1)
console.log(codes(V, s))
