import { V, P, Q, show, play, outs, invariants } from './lib.mjs'
let s
const step = (code, i = null, quiet = false) => {
	console.log('\n>> ' + code + '   outcomes: ' + outs(s, code))
	s = play(s, code, i)
	invariants(s)
	if (!quiet) console.log(show(s))
}
console.log('=== C: the time split')
s = Q.newGame(V, { setup: 'small' })
step('(0T1)d1-c3', null, true)
step('(0T1)a4-a3', null, true)
console.log('split targets of L0:c3:', Q.splitTargets(V, s, V.topology.byName('L0:c3')).map((q) => V.topology.names[q]).join(' '))
step('L0:c3-L0~1:a3|L0~1:e3')
console.log('Black to move; keys on L+1:', Q.ordinaryMoves(V, s).map((m) => m.code).filter((c) => c.startsWith('(+1')).join(' '))
step('(+1T1)b4-b3')
console.log('danger W', Q.royalDanger(V, s, 0), 'submit legal', Q.isLegal(V, s, 'submit'))
console.log('\n=== E: twins')
s = Q.newGame(V, { setup: 'small' })
step('L0:d1-L0:c3|L0:e3', null, true)
step('(0T1)a4-a3', null, true)
step('(0T2)b2-b3', null, true)
step('(0T2)d5>>(0T1)d3')
console.log('budget W', Q.budget(s, 0))
step('?L−1:c3', 1)
console.log('\n=== G: Missed still opens the door')
s = Q.newGame(V, { setup: 'small' })
step('L0:d1-L0:c3|L0:e3', null, true)
step('(0T1)a4-a3', null, true)
step('(0T2)c3>>(0T1)c5', 0)
