import { ANTI as V, legalC, branchesC, mustCapture } from './proto.mjs'
import { stateOf, show, newGame } from '../c960/lib.mjs'
import { outcomes, applyOutcome, legalMoves, budget, T } from '/home/user/Quantum_Chess/src/variants/core/quantum.js'
const hr = (t) => console.log('\n=== ' + t)
const res = (s) => JSON.stringify(s.result)
const outsC = (s, c) => { const l = branchesC(V, s, c); return l ? l.map(b => `${b.key}${b.notes.length ? '[' + b.notes.join(';') + ']' : ''} p=${b.weight / T}`) : null }
const codesC = (s, splits = false) => legalC(V, s, splits).map(m => m.code)
const play = (s, c, i = 0) => { if (!branchesC(V, s, c)) throw new Error('illegal ' + c); return applyOutcome(V, s, c, i) }

hr('A1 start')
let s = newGame(V)
console.log(codesC(s).length, codesC(s).includes('O-O'), JSON.stringify(s.worlds[0].b.x), res(s), V.royalTypes.size, [...V.solidTypes])
hr('A2 1.e3 b5: only f1-b5')
s = play(s, 'e2-e3'); s = play(s, 'b7-b5'); console.log(codesC(s), 'must', mustCapture(V, s))
hr('A3 choose among captures: W Ra1 Nc3, B pa8? pb5 pd5')
s = stateOf(V, [[{ a1: '0:r', c3: '0:n', a8: '1:r', b5: '1:p', h7: '1:p' }, 1]])
console.log(codesC(s))
hr('A4 king captures and is captured, no check')
s = stateOf(V, [[{ d4: '0:k', e4: '1:r', h7: '1:p' }, 1]])
console.log(codesC(s))
s = stateOf(V, [[{ a1: '0:k', h2: '0:p', a4: '1:r' }, 1]], 1)
console.log(codesC(s)); let a = play(s, 'a4-a1'); console.log(res(a), show(V, a))
hr('A5 promotion to king')
s = stateOf(V, [[{ e7: '0:p', a5: '1:p' }, 1]])
console.log(codesC(s)); a = play(s, 'e7-e8=k'); console.log(show(V, a), res(a))
hr('A6 en passant is compulsory')
s = stateOf(V, [[{ e5: '0:p', a2: '0:p', d7: '1:p', h7: '1:p' }, 1]], 1)
a = play(s, 'd7-d5'); console.log(codesC(a), outsC(a, 'e5-d6')); a = play(a, 'e5-d6'); console.log(show(V, a), res(a))
hr('A7 White captures Black last piece -> Black wins')
s = stateOf(V, [[{ a1: '0:r', a7: '1:p' }, 1]])
console.log(codesC(s)); a = play(s, 'a1-a7'); console.log(res(a))
hr('A8 stalemate win: W ph2; B ph3 nb8; Black to move b8-c6')
s = stateOf(V, [[{ h2: '0:p', h3: '1:p', b8: '1:n' }, 1]], 1)
console.log(codesC(s)); a = play(s, 'b8-c6'); console.log(res(a))
hr('A9 bishops of opposite colours draw')
s = stateOf(V, [[{ c1: '0:b', c8: '1:b', g5: '1:n' }, 1]])
console.log(codesC(s)); a = play(s, 'c1-g5'); console.log(res(a))
hr('A9b same colour bishops: no draw')
s = stateOf(V, [[{ c1: '0:b', f8: '1:b', g5: '1:n' }, 1]])
a = play(s, 'c1-g5'); console.log(res(a))

hr('A10 quantum: capture possible in one world only (ghost knight 50% e5 / 50% h5), W pd4 ng1, B ka8')
s = stateOf(V, [[{ d4: '0:p', g1: '0:n', e5: '1:n', a8: '1:k' }, 1], [{ d4: '0:p', g1: '0:n', h5: '1:n', a8: '1:k' }, 1]])
console.log('must', mustCapture(V, s), 'legal', codesC(s))
console.log('d4-e5', outsC(s, 'd4-e5'))
console.log('g1-f3 (core only, without the rule):', JSON.stringify(outcomes(V, s, 'g1-f3')), ' with rule:', outsC(s, 'g1-f3'))
hr('A11 quantum: capture try by a bishop: Captured / Moved; W Bc3 ng1 ; ghost n e5/h5 ; bishop c3-e5')
s = stateOf(V, [[{ c3: '0:b', g1: '0:n', e5: '1:n', a8: '1:k' }, 1], [{ c3: '0:b', g1: '0:n', h5: '1:n', a8: '1:k' }, 1]])
console.log('legal', codesC(s)); console.log('c3-e5', outsC(s, 'c3-e5'))
for (let i = 0; i < 2; i++) { const x = applyOutcome(V, s, 'c3-e5', i); console.log(i, show(V, x)) }
hr('A11b same, but in the h5 world another capture exists (W Rh1 hits h5): c3-e5 Captured / Missed')
s = stateOf(V, [[{ c3: '0:b', h1: '0:r', e5: '1:n', a8: '1:k' }, 1], [{ c3: '0:b', h1: '0:r', h5: '1:n', a8: '1:k' }, 1]])
console.log('legal', codesC(s)); console.log('c3-e5', outsC(s, 'c3-e5'), 'h1-h5', outsC(s, 'h1-h5'))
hr('A12 quantum: measure and split forbidden while a capture is possible; merge onto enemy allowed')
// white knight 50% c3 / 50% e3 ; black pawn d5 ; white pawn e4 attacks d5 ; knight parts attack d5 from c3 and e3
s = stateOf(V, [[{ c3: '0:n', e4: '0:p', d5: '1:p', a8: '1:k' }, 1], [{ e3: '0:n', e4: '0:p', d5: '1:p', a8: '1:k' }, 1]])
console.log('core legal', legalMoves(V, s, { splits: true }).map(m => m.code).filter(c => c.startsWith('?') || c.includes('|')))
console.log('rule legal', codesC(s, true))
console.log('c3|e3-d5', outsC(s, 'c3|e3-d5'), 'c3-d5', outsC(s, 'c3-d5'))
hr('A12b no capture possible: measure and split allowed')
s = stateOf(V, [[{ c3: '0:n', a2: '0:p', h7: '1:p', a8: '1:k' }, 1], [{ e3: '0:n', a2: '0:p', h7: '1:p', a8: '1:k' }, 1]])
console.log(codesC(s).filter(c => c.startsWith('?') || c.includes('|')), 'must', mustCapture(V, s))
hr('A13 quantum stalemate game-end roll: W ph2 ; B ph3 ke8 and knight 50% g3 / 50% b1 ; Black e8-d8')
s = stateOf(V, [[{ h2: '0:p', h3: '1:p', e8: '1:k', g3: '1:n' }, 1], [{ h2: '0:p', h3: '1:p', e8: '1:k', b1: '1:n' }, 1]], 1)
console.log('black legal', codesC(s).filter(c => c.startsWith('e8')), 'must', mustCapture(V, s))
console.log('e8-d8', outsC(s, 'e8-d8'))
for (let i = 0; i < 2; i++) { const x = applyOutcome(V, s, 'e8-d8', i); console.log(i, res(x), show(V, x)) }
hr('A14 quantum: last black piece is a ghost knight 50% f6 / 50% a6; W Bb2 hits f6 (c3 d4 e5), W also Nb8?')
s = stateOf(V, [[{ b2: '0:b', h2: '0:p', f6: '1:n' }, 1], [{ b2: '0:b', h2: '0:p', a6: '1:n' }, 1]])
console.log('legal', codesC(s)); console.log('b2-f6', outsC(s, 'b2-f6'))
for (let i = 0; i < 2; i++) { const x = applyOutcome(V, s, 'b2-f6', i); console.log(i, res(x), show(V, x)) }
hr('A15 split of a promoted king? kings are solid: no split; queen split ok when no capture')
s = stateOf(V, [[{ d1: '0:q', e1: '0:k', h7: '1:p' }, 1]])
console.log(codesC(s, true).filter(c => c.includes('|')).length, codesC(s, true).filter(c => c.startsWith('e1') && c.includes('|')))
hr('A16 capture from ghost rook: my own rook 50% a1 / 50% h1, black piece a8: must try a1-a8')
s = stateOf(V, [[{ a1: '0:r', c2: '0:p', a8: '1:n' }, 1], [{ h1: '0:r', c2: '0:p', a8: '1:n' }, 1]])
console.log('legal', codesC(s), 'a1-a8', outsC(s, 'a1-a8'))
console.log('without rule c2-c3:', JSON.stringify(outcomes(V, s, 'c2-c3')))
